modLoader="javafml"
loaderVersion="[4,)"
license="GPL-3.0"
issueTrackerURL="https://github.com/Alex-the-666/AlexsMobs/issues"

[[mods]]
modId="alexsmobs"
version="1.22.17"
displayName="Alex's Mobs"
displayURL="https://www.curseforge.com/minecraft/mc-mods/alexs-mobs"
logoFile="alexs_mobs.png"
authors="Alexthe668, Carro1001, Paint_Ninja, Raguto"
description='''New, original, engaging, and aesthetic mobs for Minecraft.'''

[[dependencies.alexsmobs]]
    modId="citadel"
    mandatory=true
    versionRange="[2.6.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.alexsmobs]]
    modId="neoforge"
    mandatory=true
    versionRange="[21.1.0,)"
    ordering="NONE"
    side="BOTH"

[modproperties.alexsmobs]
    catalogueItemIcon="alexsmobs:bear_dust"
